baseurl = "http://osrg.github.io/earthquake/"
languageCode = "en-us"
title = "Earthquake"
theme = "bootie-docs"
copyright = "CopyrightÂ© 2015 Nippon Telegraph and Telephone Corporation"
[params]
  description = "A framework of implementation level distributed system model checkers"
  withSitePosts = true
  mainMenu = ["about", "usage"]
  #noCategoryLink = true
  repositoryUrl = "https://github.com/osrg/earthquake/"
  